### ISSUE TITLE
MobX form factory library WIP

### ISSUE THREAD

**Issue by kristianmandrup** [hrgui/mobx-form-model#1]
I'm building a [mobx-form-factory](https://github.com/kristianmandrup/mobx-form-factory) based on your library. 

Would you like to help out make it happen? Could definitely use your expertise, advise etc.

So far I've created a [json-schema-to-yup](https://www.npmjs.com/package/json-schema-to-yup) library which can generate the Yup schema from a declarative specification.

**Comment by hrgui** [comment]
Hi @kristianmandrup, sorry for responding so late. 

If you find any issues with this library that affects mobx-form-factory, feel free to post an issue, in which may be a useful channel of how we can communicate. I'm sure there are bound to be issues as I keep changing the API in it's 0.x.x phase! 

As for contributing to mobx-form-factory, I don't have time to commit to contributing as I am mostly making even this package as a side project of mine. 

Closing....
